### ISSUE TITLE
Livestream-valg må inn

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMpush_to_front#6]
Lett å glemme livestream når man setter opp mønstringa. Kanskje vise den her?

**Comment by AsgeirSH** [comment]
Også fint om lokalmønstringer får beskjed allerede her om at dette er noe de må be om spesifikt, kanskje? Den infoen er ganske skjult, som gjør det kronglete å avtale med lokale produsenter.

**Comment by mariusmandal** [comment]
Er flyttet ut i egen meny nå :)
